C:\Users\anpandey\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\dispatch.py:1082: UserWarning: "`categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)
Epoch 1/10























































312/312 [==============================] - 198s 631ms/step - loss: 2.2292 - accuracy: 0.1555 - val_loss: 2.1992 - val_accuracy: 0.1814
Epoch 2/10






































































312/312 [==============================] - 228s 732ms/step - loss: 2.1184 - accuracy: 0.2247 - val_loss: 2.0508 - val_accuracy: 0.2593
Epoch 3/10






































































312/312 [==============================] - 228s 731ms/step - loss: 2.0366 - accuracy: 0.2671 - val_loss: 1.9661 - val_accuracy: 0.3058
Epoch 4/10














































































312/312 [==============================] - 258s 828ms/step - loss: 1.9543 - accuracy: 0.2988 - val_loss: 1.9322 - val_accuracy: 0.3213
Epoch 5/10












































































312/312 [==============================] - 251s 805ms/step - loss: 1.9002 - accuracy: 0.3278 - val_loss: 1.8764 - val_accuracy: 0.3309
Epoch 6/10















































































312/312 [==============================] - 260s 835ms/step - loss: 1.8410 - accuracy: 0.3498 - val_loss: 1.8257 - val_accuracy: 0.3559
Epoch 7/10














































































312/312 [==============================] - 259s 832ms/step - loss: 1.7890 - accuracy: 0.3740 - val_loss: 1.7498 - val_accuracy: 0.3903
Epoch 8/10














































































312/312 [==============================] - 268s 861ms/step - loss: 1.7216 - accuracy: 0.3992 - val_loss: 1.6249 - val_accuracy: 0.4317
Epoch 9/10



















































































312/312 [==============================] - 277s 889ms/step - loss: 1.6425 - accuracy: 0.4288 - val_loss: 1.5260 - val_accuracy: 0.4708
Epoch 10/10























































































312/312 [==============================] - 288s 925ms/step - loss: 1.5543 - accuracy: 0.4606 - val_loss: 1.4464 - val_accuracy: 0.5085
Traceback (most recent call last):
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 945, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 164, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1976, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2011, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Users\anpandey\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\anpandey\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\anpandey\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\anpandey\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\anpandey\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\cs6910_assignments\CS6910_Assignment2\cnn_image_classifier.py", line 191, in <module>
    history = model.fit(
  File "C:\Users\anpandey\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\integration\keras\keras.py", line 168, in new_v2
    return old_v2(*args, **kwargs)
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 204, in trace_dispatch
    return thread_trace_func(frame, event, arg)
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 440, in __call__
    ).trace_dispatch(frame, event, arg)
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 945, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 164, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1976, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "c:\Users\anpandey\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2011, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
Exception ignored in: <module 'threading' from 'C:\\Users\\anpandey\\AppData\\Local\\Programs\\Python\\Python310\\lib\\threading.py'>
Traceback (most recent call last):
  File "C:\Users\anpandey\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1560, in _shutdown
    lock.acquire()
KeyboardInterrupt: